### ISSUE TITLE
Support for Rails 4?

### ISSUE THREAD

**Issue by fabrouy** [actmd/abraham#11]
Hello guys,

Is there a reason why there's no support for Rails 4? 

Thank you!

**Comment by jabbett** [comment]
I suppose the only reason is that I've only used Rails 5 ;)

Happy to help make it work if you can point out where the incompatibilities might be.

**Comment by fabrouy** [comment]
I will give it a try in Rails 4 and get back.

**Comment by Velora** [comment]
@fabrouy did you have any issues with this in Rails 4? I am looking to use this in a Rails 4 app as well. Thanks!

**Comment by willjohnson** [comment]
This was the issue I had when trying to install with Rails 4:

Bundler could not find compatible versions for gem "rails":
In snapshot (Gemfile.lock):
rails (= 4.2.7.1)
In Gemfile:
rails (= 4.2.7.1)
abraham was resolved to 1.2, which depends on
rails (>= 5.0.0.1, ~> 5.0.0)

**Comment by Velora** [comment]
@willjohnson since abraham is not compatible with rails 4, the gem requires rails 5 or above. That is what that error means.

**Comment by willjohnson** [comment]
@Velora Understand but the maintainer offered above to help make it work if we can point out where the incompatibilities are :)

**Comment by seanfcarroll** [comment]
Close this issue out?

**Comment by willjohnson** [comment]
@seanfcarroll I ended up using a JS solution here so no longer an issue for me.

**Comment by seanfcarroll** [comment]
@fabrouy can this issue be closed?

**Comment by jabbett** [comment]
I just dropped Rails 5.1 testing since I couldn't get it to work reliably in Travis, so I think Rails 4 is beyond me :)
