### ISSUE TITLE
Web UI?

### ISSUE THREAD

**Issue by bborn** [actmd/abraham#18]
Thanks for this gem - it looks great. Wondering if you've thought about building out any kind of web ui for managing the tours (rather than yaml). It'd be great to let non-technical members of my team create/manage tours. There are a million SaaS offerings for this out there, but they're 1) expensive and 2) not great.

Just wondering what thought has been given to this before I go ahead and start building in this direction myself.

**Comment by jabbett** [comment]
Hi, @bborn! Our company worked with a SaaS tour app before we implemented Abraham -- I understand the position you're in.

A major challenge we had with using such a tour app is keeping the tours in sync with the interface. Any changes to our UI code had the potential to break our tours. By committing Abraham tour specifications within the codebase, we could better ensure that tours were matched with the right code (and we can, in theory, write integration tests to that effect).

Now, that's more of a constraint to a tour-builder UI than a deal-breaker. Perhaps we could design a browser extension that makes it easier to select elements on the page and compose the tour content against it, then spit out a YAML file that your non-technical teammate would then e-mail/chat to a developer.

Or--more bare-bones to start--we could write a "Defining a tour for non-developers" tutorial that explains how to write in YAML and how to use a browser's developer tools to find an element and copy its selector?

**Comment by bborn** [comment]
@jabbett thanks for your thoughts. We ended up going with Intercom's tour product for the time being, but will definitely revisit this if we change course.
