### ISSUE TITLE
Configure my application so tours don't appear in test environment by default

### ISSUE THREAD

**Issue by jabbett** [actmd/abraham#2]
When we run in-browser tests, a Shepherd step will sometimes get in the way of an element positioned beneath it. If we're running tests that aren't explicitly testing product tours, it would be nice if the tours didn't appear.

**Comment by rroppolo** [comment]
One option is to remove the tours from the abraham configuration object.
In the in-browser test's config file, add:
```
Rails.application.configure do
  config.abraham.tours = {}
end
```

**Comment by jabbett** [comment]
@rroppolo I will add a note in the README and call it a day.
