### ISSUE TITLE
How to handle controllers with the same name?

### ISSUE THREAD

**Issue by marwann** [actmd/abraham#38]
Hi there,

Thanks for making Abraham :) 

My issue is that I have some namespaced controllers / actions with the same name, eg. : 
- `User::Dashboard#index`
- `Admin::Dashboard#index`

Namespaces aren't taken into account in Abraham so I had put my yml file inside `tours/dashboard/index.en.yml` which results in the tour displaying in both dashboards.

I've tried changing the initializer to take subfolders like `tours/admin/dashboard/index.en.yml` into account but with no luck, Abraham doesn't recognize the controller.

Any clue?

Thanks

**Comment by seanfcarroll** [comment]
This could probably done fairly easily by referring to `controller_path` instead of `controller_name` [when making the Ajax call](https://github.com/actmd/abraham/blob/master/app/views/application/_abraham.html.erb#L6):

```js
  tour.on("complete", function() {
    // ajax
    return $.ajax({
      url: "/abraham_histories/",
      type: "POST",
      dataType: "json",
      contentType: "application/json",
      data: JSON.stringify({
        authenticity_token: '<%= form_authenticity_token %>',
        controller_name: '<%= controller_name %>',
        action_name: '<%= action_name %>',
        tour_name: '<%= tour_name %>'
      })
    });
```
Supporting changes would be needed in the [controller](https://github.com/actmd/abraham/blob/master/app/controllers/abraham_histories_controller.rb) and database table.

http://api.rubyonrails.org/classes/AbstractController/Base.html#method-i-controller_path

**Comment by jabbett** [comment]
Hi, @marwann! Thanks for your question and apologies for the frustration! We obviously didn't anticipate namespaces :(

I like @seanfcarroll's `controller_path` idea, though we'd have to figure out backward compatibility.

If we simple changed the code to use `controller_path`, applications that had already been using Abraham would suddenly see all their old tours reappear ;)

**Comment by jabbett** [comment]
@seanfcarroll We actually discussed this topic among our team this morning, we're going to test your solution out here and try to get it included ASAP ;)

**Comment by seanfcarroll** [comment]
@jabbett glad it was helpful!

**Comment by jabbett** [comment]
The tricky part was rewriting the initializer to load the yaml files while retaining the controller path. But now that I've figured that out, I expect to get this tested and released today.
