### ISSUE TITLE
Launch tour on demand

### ISSUE THREAD

**Issue by ehausen** [actmd/abraham#42]
Is it possible to start tour on demand by calling a function or something?

Would it for example be possible to implement a "Launch Tour" button on a page?

**Comment by seanfcarroll** [comment]
The simple way to do this is to have a button which deletes the entry from the `abraham_histories` table and then redirects back to the same page.

**Comment by jabbett** [comment]
@ehausen FYI, the last release of Abraham includes the ability to start a tour on demand — have a look at the updated README.
