### ISSUE TITLE
CI is failing against Rails 6

### ISSUE THREAD

**Issue by seanfcarroll** [actmd/abraham#46]
https://travis-ci.com/github/actmd/abraham/jobs/497555469

**Comment by jabbett** [comment]
In `test/dummy/config/application.rb`, there's a configuration that must be done prior to Rails 6.1, but must not be done in Rails 6.1 and above:

```
config.active_record.sqlite3.represent_boolean_as_integer = true
```

There may be a far more elegant way to solve this, but we can wrap it in some version checking like so:

```
# This configuration is no longer necessary with Rails 6.1+
unless Rails::VERSION::MAJOR >= 6 && Rails::VERSION::MINOR >= 1
  config.active_record.sqlite3.represent_boolean_as_integer = true
end
```
