### ISSUE TITLE
Manually activate a tour (e.g. on click)

### ISSUE THREAD

**Issue by prschmid** [actmd/abraham#5]
For example when hovering over the "starred items" icon on Slack, you get a nice popup as follows

![screen shot 2016-12-29 at 9 11 13 am](https://cloud.githubusercontent.com/assets/710710/21545648/3cbb5622-cda7-11e6-9ec1-4706afab9a78.png)

Then when you click on the icon, the (single step) tour begins

![screen shot 2016-12-29 at 9 11 20 am](https://cloud.githubusercontent.com/assets/710710/21545659/4f76d84a-cda7-11e6-8cd1-7aa973f969ce.png)

The nice thing is that the "hover" step doesn't need to be there (e.g. on mobile there is no "hover") and so it works nicely on both desktop and mobile.

**Comment by kofronpi** [comment]
@prschmid Really cool idea ! This gem wraps [shepherd.js](https://github.com/HubSpot/shepherd/), did you open an issue there? :)

**Comment by jabbett** [comment]
@kofronpi I think this is fully implementable without any changes to shepherd.js. Abraham could define a single-step tour and tie the `start()` action to a click event on a particular DOM element.

**Comment by kofronpi** [comment]
@jabbett interesting ! you'd have to carefully consider what is configurable at the abraham-level and what is configurable at the shepherd-level (see the issue I opened - #8)

**Comment by seanfcarroll** [comment]
Just wondering if this suggestion is under consideration? It's a useful feature.

**Comment by jabbett** [comment]
Just thinking through how this might be implemented:

* Rework `AbrahamHelper.abraham_tour` to pass all a page's tours, regardless of completion, to the partial, along with a list of tour names that have been completed
* Have the ability to indicate in the tour config YAML whether a tour should only be manually-activated
* Update `_abraham.html.erb` to
  * render the JavaScript initialization of all tours, not just one
  * auto-start a tour on page load only if it's:
    * next in line
    * not manual
    * not completed
    * not already dismissed for later
    * not missing its first attachTo element
  * register JavaScript event listeners to make each tour individually startable by name

**Comment by seanfcarroll** [comment]
Can also be done by deleting the previous tour entry and reloading the page https://github.com/actmd/abraham/issues/42
