### ISSUE TITLE
Sourcemap errors

### ISSUE THREAD

**Issue by seanfcarroll** [actmd/abraham#54]
Is anyone else getting sourcemap errors in development? I think I have following the install instructions correctly but am seeing this error in my Rails logs

```
ActionController::RoutingError (No route matches [GET] "/assets/shepherd.js.map"):

actionpack (5.2.5) lib/action_dispatch/middleware/debug_exceptions.rb:65:in `call'
rollbar (3.0.1) lib/rollbar/middleware/rails/show_exceptions.rb:22:in `call_with_rollbar'
rack-contrib (2.1.0) lib/rack/contrib/response_headers.rb:17:in `call'
meta_request (0.7.0) lib/meta_request/middlewares/headers.rb:16:in `call'
actionpack (5.2.5) lib/action_dispatch/middleware/show_exceptions.rb:33:in `call'
railties (5.2.5) lib/rails/rack/logger.rb:38:in `call_app'
railties (5.2.5) lib/rails/rack/logger.rb:26:in `block in call'
etc
```

**Comment by jabbett** [comment]
The Shepherd package's JS files do point to sourcemaps, e.g.

```js
//# sourceMappingURL=shepherd.js.map
```

Your browser will request these sourcemap files when you open your debugger console. When I run the dummy test app, I see this in my Rails log:

```
127.0.0.1 - - [18/Jun/2021:09:51:11 EDT] "GET /assets/shepherd.js/dist/js/shepherd.source.js HTTP/1.1" 200 166319
- -> /assets/shepherd.js/dist/js/shepherd.source.js
```

...so the asset pipeline seems to have no problem delivering the sourcemap.

How are you including/requiring the abraham Javascript in your project? What browser are you using? Let us know! :)

**Comment by seanfcarroll** [comment]
@jabbett this issue has gone away, it must have been something specific to my setup.

Closing this.
