### ISSUE TITLE
ERROR in ./node_modules/abraham/cli.js 1:0 Module parse failed: Unexpected character '#' (1:0)

### ISSUE THREAD

**Issue by mathewross** [actmd/abraham#55]
Not sure if this is more a webpack issue than with abraham, but I'm getting the error:

ERROR in ./node_modules/abraham/cli.js 1:0
Module parse failed: Unexpected character '#' (1:0)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> #!/usr/bin/env node
| 'use strict';

The tour works fine in my application, but this error is constantly in the console and I'm having issues with builds because of it. I've tried a webpack loader as suggested in https://github.com/webpack/webpack/issues/4603, however that's not working so I wondered if anyone had come across this and there was a fix?

**Comment by jabbett** [comment]
Hmm, Abraham doesn't have a JS file called `cli.js`

Do you know where in your code that file is requested/referenced?
